/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_xlsxparser_free: (a: number, b: number) => void;
export const xlsxparser_load: (a: number, b: number, c: number) => [number, number, number, number];
export const xlsxparser_new: () => number;
export const __wbg_formulaengine_free: (a: number, b: number) => void;
export const formulaengine_evaluate_all: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const formulaengine_evaluate_cell: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const formulaengine_get_dependents: (a: number, b: number, c: number) => [number, number];
export const formulaengine_invalidate: (a: number, b: number, c: number) => void;
export const formulaengine_new: () => number;
export const formulaengine_set_named_ranges: (a: number, b: number, c: number) => [number, number];
export const __wbg_xlsxwriter_free: (a: number, b: number) => void;
export const xlsxwriter_save: (a: number, b: number, c: number) => [number, number, number, number];
export const xlsxwriter_new: () => number;
export const greet: () => [number, number];
export const init_panic_hook: () => void;
export const __wbg_contextmenumanager_free: (a: number, b: number) => void;
export const __wbg_tableops_free: (a: number, b: number) => void;
export const contextmenumanager_get_context_menu: (a: number, b: number, c: number) => [number, number, number, number];
export const create_simple_xlsx: () => [number, number, number, number];
export const tableops_add_table_column: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const tableops_convert_to_range: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const tableops_create_table: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number, number, number];
export const tableops_remove_table_column: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const tableops_rename_table: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const tableops_resize_table: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const tableops_set_table_style: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const tableops_set_totals_row: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
export const tableops_toggle_filter: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const contextmenumanager_new: () => number;
export const tableops_new: () => number;
export const __wbg_viewportmanager_free: (a: number, b: number) => void;
export const viewportmanager_get_viewport: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
export const viewportmanager_new: () => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
