/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import 'mocha';
import * as assert from 'assert';
import { renderProfileRule } from '../profileRuleTemplate';
import { SAMPLE_CASE_IDENTITY } from '../sampleCase';
import { UserProfile } from '../types';

suite('sampleCase', () => {
	test('SAMPLE_CASE_IDENTITY keeps unmistakably fictional markers', () => {
		assert.deepStrictEqual(SAMPLE_CASE_IDENTITY, {
			caseName: '[SAMPLE — NOT A REAL CASE] Fictional Worker v. Demo Employer Co.',
			claimNumber: 'SAMPLE-0000-NOT-REAL',
			clientName: 'Alex Sampleton (FICTIONAL — practice data only)',
			opposingParty: 'Demo Employer Co. (FICTIONAL)',
			opposingRepresentative: 'Jordan Example, Esq. (FICTIONAL)',
		});
	});
});

suite('renderProfileRule', () => {
	test('pins persona-group profile instructions snapshots', () => {
		const emptyProfile: UserProfile = {
			name: '',
			organization: '',
			role: '',
			practiceArea: '',
			focusArea: '',
			citationStyle: '',
			country: '',
			stateProvince: '',
			city: '',
			jurisdiction: '',
		};

		assert.deepStrictEqual({
			legal: renderProfileRule({
				name: 'Alex Advocate',
				organization: 'Sample Legal LLP',
				role: 'Lawyer',
				practiceArea: 'Workers\' Compensation',
				country: 'Canada',
				stateProvince: 'British Columbia',
				city: 'Vancouver',
				jurisdiction: 'BC WCB',
			}),
			self: renderProfileRule({
				name: 'Sam Worker',
				role: 'Injured Worker',
				country: 'Canada',
				stateProvince: 'Ontario',
				city: 'Toronto',
				jurisdiction: 'Ontario WSIB',
			}),
			educationStudent: renderProfileRule({
				name: 'Casey Student',
				organization: 'UBC',
				role: 'Student',
				focusArea: 'Labour Law',
				citationStyle: 'McGill Guide',
				country: 'Canada',
				stateProvince: 'British Columbia',
			}),
			educationTeacher: renderProfileRule({
				name: 'Taylor Teacher',
				organization: 'Metro High',
				role: 'Teacher',
				focusArea: 'Civics / Grade 11',
				citationStyle: 'APA',
				country: 'Canada',
				stateProvince: 'Ontario',
			}),
			research: renderProfileRule({
				name: 'Riley Researcher',
				organization: 'Institute',
				role: 'Researcher',
				focusArea: 'Occupational health',
				citationStyle: 'APA',
				country: 'Canada',
				stateProvince: 'Alberta',
			}),
			office: renderProfileRule({
				name: 'Owen Office',
				organization: 'Acme Corp',
				role: 'Office Worker',
				focusArea: 'Claims intake',
			}),
			developer: renderProfileRule({
				name: 'Dana Dev',
				organization: 'SafeAppeals',
				role: 'Software Developer',
				focusArea: 'TypeScript / Electron',
			}),
			empty: renderProfileRule(emptyProfile),
			unknownRole: renderProfileRule({
				name: 'Pat Custom',
				organization: 'Custom Org',
				role: 'Claims adjuster',
				practiceArea: 'Disability',
				country: 'Canada',
				stateProvince: 'BC',
				city: 'Victoria',
				jurisdiction: 'BC WCB',
			}),
		}, {
			legal: [
				'---',
				'description: \'Safe Appeals user profile — who the user is and how they work\'',
				'applyTo: \'**\'',
				'---',
				'',
				'# About the Safe Appeals user',
				'',
				'This profile was set up during the Safe Appeals welcome onboarding',
				'(rerun "Safe Appeals Case: Set Up Profile" to change it).',
				'',
				'- **Name:** Alex Advocate',
				'- **Firm / organization:** Sample Legal LLP',
				'- **Role:** Lawyer',
				'- **Practice area:** Workers\' Compensation',
				'- **Country:** Canada',
				'- **State / province:** British Columbia',
				'- **City:** Vancouver',
				'- **Compensation board / tribunal:** BC WCB',
				'',
				'When drafting documents, correspondence, or appeals, write from this',
				'person\'s perspective and jurisdiction unless the case brief (AGENTS.md',
				'in the case folder) says otherwise. Case-specific facts always take',
				'precedence over this profile.',
				'',
				'## Research & citations — all work, legal or business',
				'',
				'- End every research answer with a **Sources** section: one markdown link per source, each on its own line.',
				'- Cite with a pinpoint, not just a link: section, paragraph, or page (e.g. "s. 5(1)", "para. 32", "p. 14"). Never cite a bare homepage.',
				'- Prefer primary and official sources (legislation, tribunal decisions, board policy manuals, government sites, vendor documentation) over blogs and summaries.',
				'- Never invent a citation, quote, case name, figure, or deadline. If you cannot find a source, say so plainly instead of guessing.',
				'- Mark any citation you did not open and read in this session as **[unverified]**, and tell the user to confirm it against the original before relying on it.',
				'- Treat deadlines and limitation periods as unverified until the user confirms them against the board or tribunal\'s official source.',
				'- Quote exactly and sparingly; paraphrase everything else and attribute it.',
				'- When a source can change over time (rates, policies, forms, deadlines), note the date you accessed it.',
				'- Match the citation style already used in the user\'s documents; do not impose one.',
				'',
				'## Working with this user',
				'',
				'Write for a legal professional: formal register, jurisdiction-correct citation format with pinpoint paragraphs, and assume the user will verify every authority on a primary database before filing.',
				'',
			].join('\n'),
			self: [
				'---',
				'description: \'Safe Appeals user profile — who the user is and how they work\'',
				'applyTo: \'**\'',
				'---',
				'',
				'# About the Safe Appeals user',
				'',
				'This profile was set up during the Safe Appeals welcome onboarding',
				'(rerun "Safe Appeals Case: Set Up Profile" to change it).',
				'',
				'- **Name:** Sam Worker',
				'- **Role:** Injured Worker',
				'- **Country:** Canada',
				'- **State / province:** Ontario',
				'- **City:** Toronto',
				'- **Compensation board / tribunal:** Ontario WSIB',
				'',
				'When drafting documents, correspondence, or appeals, write from this',
				'person\'s perspective and jurisdiction unless the case brief (AGENTS.md',
				'in the case folder) says otherwise. Case-specific facts always take',
				'precedence over this profile.',
				'',
				'## Research & citations — all work, legal or business',
				'',
				'- End every research answer with a **Sources** section: one markdown link per source, each on its own line.',
				'- Cite with a pinpoint, not just a link: section, paragraph, or page (e.g. "s. 5(1)", "para. 32", "p. 14"). Never cite a bare homepage.',
				'- Prefer primary and official sources (legislation, tribunal decisions, board policy manuals, government sites, vendor documentation) over blogs and summaries.',
				'- Never invent a citation, quote, case name, figure, or deadline. If you cannot find a source, say so plainly instead of guessing.',
				'- Mark any citation you did not open and read in this session as **[unverified]**, and tell the user to confirm it against the original before relying on it.',
				'- Treat deadlines and limitation periods as unverified until the user confirms them against the board or tribunal\'s official source.',
				'- Quote exactly and sparingly; paraphrase everything else and attribute it.',
				'- When a source can change over time (rates, policies, forms, deadlines), note the date you accessed it.',
				'- Match the citation style already used in the user\'s documents; do not impose one.',
				'',
				'## Working with this user',
				'',
				'Write in plain language and define legal terms on first use. When research turns up a statute, policy, decision, or ground that appears to favor the user, propose it as a candidate argument with sources and pinpoints, and explain why it may help — then require the user to verify it against primary materials before relying on it. This is a research and drafting aid, not a substitute for the user\'s judgment or a lawyer.',
				'',
			].join('\n'),
			educationStudent: [
				'---',
				'description: \'Safe Appeals user profile — who the user is and how they work\'',
				'applyTo: \'**\'',
				'---',
				'',
				'# About the Safe Appeals user',
				'',
				'This profile was set up during the Safe Appeals welcome onboarding',
				'(rerun "Safe Appeals Case: Set Up Profile" to change it).',
				'',
				'- **Name:** Casey Student',
				'- **School / institution:** UBC',
				'- **Role:** Student',
				'- **Field of study:** Labour Law',
				'- **Citation style:** McGill Guide',
				'- **Country:** Canada',
				'- **State / province:** British Columbia',
				'',
				'Frame answers and drafts for this person\'s work and background unless the current workspace or task says otherwise.',
				'',
				'## Research & citations — all work, legal or business',
				'',
				'- End every research answer with a **Sources** section: one markdown link per source, each on its own line.',
				'- Cite with a pinpoint, not just a link: section, paragraph, or page (e.g. "s. 5(1)", "para. 32", "p. 14"). Never cite a bare homepage.',
				'- Prefer primary and official sources (legislation, tribunal decisions, board policy manuals, government sites, vendor documentation) over blogs and summaries.',
				'- Never invent a citation, quote, case name, figure, or deadline. If you cannot find a source, say so plainly instead of guessing.',
				'- Mark any citation you did not open and read in this session as **[unverified]**, and tell the user to confirm it against the original before relying on it.',
				'- Treat deadlines and limitation periods as unverified until the user confirms them against the board or tribunal\'s official source.',
				'- Quote exactly and sparingly; paraphrase everything else and attribute it.',
				'- When a source can change over time (rates, policies, forms, deadlines), note the date you accessed it.',
				'- Match the citation style already used in the user\'s documents; do not impose one.',
				'',
				'## Working with this user',
				'',
				'Explain the reasoning, not just the answer, and cite so every claim can be traced to its source; flag the primary materials the user should read themselves.',
				'',
			].join('\n'),
			educationTeacher: [
				'---',
				'description: \'Safe Appeals user profile — who the user is and how they work\'',
				'applyTo: \'**\'',
				'---',
				'',
				'# About the Safe Appeals user',
				'',
				'This profile was set up during the Safe Appeals welcome onboarding',
				'(rerun "Safe Appeals Case: Set Up Profile" to change it).',
				'',
				'- **Name:** Taylor Teacher',
				'- **School / institution:** Metro High',
				'- **Role:** Teacher',
				'- **Subject / level:** Civics / Grade 11',
				'- **Citation style:** APA',
				'- **Country:** Canada',
				'- **State / province:** Ontario',
				'',
				'Frame answers and drafts for this person\'s work and background unless the current workspace or task says otherwise.',
				'',
				'## Research & citations — all work, legal or business',
				'',
				'- End every research answer with a **Sources** section: one markdown link per source, each on its own line.',
				'- Cite with a pinpoint, not just a link: section, paragraph, or page (e.g. "s. 5(1)", "para. 32", "p. 14"). Never cite a bare homepage.',
				'- Prefer primary and official sources (legislation, tribunal decisions, board policy manuals, government sites, vendor documentation) over blogs and summaries.',
				'- Never invent a citation, quote, case name, figure, or deadline. If you cannot find a source, say so plainly instead of guessing.',
				'- Mark any citation you did not open and read in this session as **[unverified]**, and tell the user to confirm it against the original before relying on it.',
				'- Treat deadlines and limitation periods as unverified until the user confirms them against the board or tribunal\'s official source.',
				'- Quote exactly and sparingly; paraphrase everything else and attribute it.',
				'- When a source can change over time (rates, policies, forms, deadlines), note the date you accessed it.',
				'- Match the citation style already used in the user\'s documents; do not impose one.',
				'',
				'## Working with this user',
				'',
				'Explain concepts at the level of the class being taught, and cite source materials with page or section pinpoints so they can go straight into handouts and slides. Support drafting lessons, assignments, rubrics, and exemplars — but when asked to complete a student\'s assessed work, produce marking guidance and worked examples instead of a finished submission.',
				'',
			].join('\n'),
			research: [
				'---',
				'description: \'Safe Appeals user profile — who the user is and how they work\'',
				'applyTo: \'**\'',
				'---',
				'',
				'# About the Safe Appeals user',
				'',
				'This profile was set up during the Safe Appeals welcome onboarding',
				'(rerun "Safe Appeals Case: Set Up Profile" to change it).',
				'',
				'- **Name:** Riley Researcher',
				'- **Institution / affiliation:** Institute',
				'- **Role:** Researcher',
				'- **Research field:** Occupational health',
				'- **Citation style:** APA',
				'- **Country:** Canada',
				'- **State / province:** Alberta',
				'',
				'Frame answers and drafts for this person\'s work and background unless the current workspace or task says otherwise.',
				'',
				'## Research & citations — all work, legal or business',
				'',
				'- End every research answer with a **Sources** section: one markdown link per source, each on its own line.',
				'- Cite with a pinpoint, not just a link: section, paragraph, or page (e.g. "s. 5(1)", "para. 32", "p. 14"). Never cite a bare homepage.',
				'- Prefer primary and official sources (legislation, tribunal decisions, board policy manuals, government sites, vendor documentation) over blogs and summaries.',
				'- Never invent a citation, quote, case name, figure, or deadline. If you cannot find a source, say so plainly instead of guessing.',
				'- Mark any citation you did not open and read in this session as **[unverified]**, and tell the user to confirm it against the original before relying on it.',
				'- Treat deadlines and limitation periods as unverified until the user confirms them against the board or tribunal\'s official source.',
				'- Quote exactly and sparingly; paraphrase everything else and attribute it.',
				'- When a source can change over time (rates, policies, forms, deadlines), note the date you accessed it.',
				'- Match the citation style already used in the user\'s documents; do not impose one.',
				'',
				'## Working with this user',
				'',
				'Cite academically (author, year, pinpoint) and prefer peer-reviewed or primary sources; keep findings clearly separate from your own synthesis.',
				'',
			].join('\n'),
			office: [
				'---',
				'description: \'Safe Appeals user profile — who the user is and how they work\'',
				'applyTo: \'**\'',
				'---',
				'',
				'# About the Safe Appeals user',
				'',
				'This profile was set up during the Safe Appeals welcome onboarding',
				'(rerun "Safe Appeals Case: Set Up Profile" to change it).',
				'',
				'- **Name:** Owen Office',
				'- **Company / organization:** Acme Corp',
				'- **Role:** Office Worker',
				'- **Works on:** Claims intake',
				'',
				'Frame answers and drafts for this person\'s work and background unless the current workspace or task says otherwise.',
				'',
				'## Research & citations — all work, legal or business',
				'',
				'- End every research answer with a **Sources** section: one markdown link per source, each on its own line.',
				'- Cite with a pinpoint, not just a link: section, paragraph, or page (e.g. "s. 5(1)", "para. 32", "p. 14"). Never cite a bare homepage.',
				'- Prefer primary and official sources (legislation, tribunal decisions, board policy manuals, government sites, vendor documentation) over blogs and summaries.',
				'- Never invent a citation, quote, case name, figure, or deadline. If you cannot find a source, say so plainly instead of guessing.',
				'- Mark any citation you did not open and read in this session as **[unverified]**, and tell the user to confirm it against the original before relying on it.',
				'- Treat deadlines and limitation periods as unverified until the user confirms them against the board or tribunal\'s official source.',
				'- Quote exactly and sparingly; paraphrase everything else and attribute it.',
				'- When a source can change over time (rates, policies, forms, deadlines), note the date you accessed it.',
				'- Match the citation style already used in the user\'s documents; do not impose one.',
				'',
				'## Working with this user',
				'',
				'Keep drafts concise and action-oriented; cite internal documents by title and section, external claims by link, and flag every figure — rates, dates, amounts — as needing confirmation before it leaves the building.',
				'',
			].join('\n'),
			developer: [
				'---',
				'description: \'Safe Appeals user profile — who the user is and how they work\'',
				'applyTo: \'**\'',
				'---',
				'',
				'# About the Safe Appeals user',
				'',
				'This profile was set up during the Safe Appeals welcome onboarding',
				'(rerun "Safe Appeals Case: Set Up Profile" to change it).',
				'',
				'- **Name:** Dana Dev',
				'- **Company / team:** SafeAppeals',
				'- **Role:** Software Developer',
				'- **Languages / stack:** TypeScript / Electron',
				'',
				'Frame answers and drafts for this person\'s work and background unless the current workspace or task says otherwise.',
				'',
				'## Research & citations — all work, legal or business',
				'',
				'- End every research answer with a **Sources** section: one markdown link per source, each on its own line.',
				'- Cite with a pinpoint, not just a link: section, paragraph, or page (e.g. "s. 5(1)", "para. 32", "p. 14"). Never cite a bare homepage.',
				'- Prefer primary and official sources (legislation, tribunal decisions, board policy manuals, government sites, vendor documentation) over blogs and summaries.',
				'- Never invent a citation, quote, case name, figure, or deadline. If you cannot find a source, say so plainly instead of guessing.',
				'- Mark any citation you did not open and read in this session as **[unverified]**, and tell the user to confirm it against the original before relying on it.',
				'- Treat deadlines and limitation periods as unverified until the user confirms them against the board or tribunal\'s official source.',
				'- Quote exactly and sparingly; paraphrase everything else and attribute it.',
				'- When a source can change over time (rates, policies, forms, deadlines), note the date you accessed it.',
				'- Match the citation style already used in the user\'s documents; do not impose one.',
				'',
				'## Working with this user',
				'',
				'Link the exact documentation page and version, prefer official docs and changelogs over tutorials, and verify library claims against what\'s actually installed in the project.',
				'',
			].join('\n'),
			empty: [
				'---',
				'description: \'Safe Appeals user profile — who the user is and how they work\'',
				'applyTo: \'**\'',
				'---',
				'',
				'# About the Safe Appeals user',
				'',
				'This profile was set up during the Safe Appeals welcome onboarding',
				'(rerun "Safe Appeals Case: Set Up Profile" to change it).',
				'',
				'When drafting documents, correspondence, or appeals, write from this',
				'person\'s perspective and jurisdiction unless the case brief (AGENTS.md',
				'in the case folder) says otherwise. Case-specific facts always take',
				'precedence over this profile.',
				'',
				'## Research & citations — all work, legal or business',
				'',
				'- End every research answer with a **Sources** section: one markdown link per source, each on its own line.',
				'- Cite with a pinpoint, not just a link: section, paragraph, or page (e.g. "s. 5(1)", "para. 32", "p. 14"). Never cite a bare homepage.',
				'- Prefer primary and official sources (legislation, tribunal decisions, board policy manuals, government sites, vendor documentation) over blogs and summaries.',
				'- Never invent a citation, quote, case name, figure, or deadline. If you cannot find a source, say so plainly instead of guessing.',
				'- Mark any citation you did not open and read in this session as **[unverified]**, and tell the user to confirm it against the original before relying on it.',
				'- Treat deadlines and limitation periods as unverified until the user confirms them against the board or tribunal\'s official source.',
				'- Quote exactly and sparingly; paraphrase everything else and attribute it.',
				'- When a source can change over time (rates, policies, forms, deadlines), note the date you accessed it.',
				'- Match the citation style already used in the user\'s documents; do not impose one.',
				'',
			].join('\n'),
			unknownRole: [
				'---',
				'description: \'Safe Appeals user profile — who the user is and how they work\'',
				'applyTo: \'**\'',
				'---',
				'',
				'# About the Safe Appeals user',
				'',
				'This profile was set up during the Safe Appeals welcome onboarding',
				'(rerun "Safe Appeals Case: Set Up Profile" to change it).',
				'',
				'- **Name:** Pat Custom',
				'- **Firm / organization:** Custom Org',
				'- **Role:** Claims adjuster',
				'- **Practice area:** Disability',
				'- **Country:** Canada',
				'- **State / province:** BC',
				'- **City:** Victoria',
				'- **Compensation board / tribunal:** BC WCB',
				'',
				'When drafting documents, correspondence, or appeals, write from this',
				'person\'s perspective and jurisdiction unless the case brief (AGENTS.md',
				'in the case folder) says otherwise. Case-specific facts always take',
				'precedence over this profile.',
				'',
				'## Research & citations — all work, legal or business',
				'',
				'- End every research answer with a **Sources** section: one markdown link per source, each on its own line.',
				'- Cite with a pinpoint, not just a link: section, paragraph, or page (e.g. "s. 5(1)", "para. 32", "p. 14"). Never cite a bare homepage.',
				'- Prefer primary and official sources (legislation, tribunal decisions, board policy manuals, government sites, vendor documentation) over blogs and summaries.',
				'- Never invent a citation, quote, case name, figure, or deadline. If you cannot find a source, say so plainly instead of guessing.',
				'- Mark any citation you did not open and read in this session as **[unverified]**, and tell the user to confirm it against the original before relying on it.',
				'- Treat deadlines and limitation periods as unverified until the user confirms them against the board or tribunal\'s official source.',
				'- Quote exactly and sparingly; paraphrase everything else and attribute it.',
				'- When a source can change over time (rates, policies, forms, deadlines), note the date you accessed it.',
				'- Match the citation style already used in the user\'s documents; do not impose one.',
				'',
			].join('\n'),
		});
	});
});
