/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Feature availability for hard-disable / BYO gates in the host. */
export declare function capabilities(): Capabilities

/** Capability flags reported to the extension host. */
export interface Capabilities {
  hybrid: boolean
  rerank: boolean
  queryProcessor: boolean
  modelsPresent: boolean
  /** True when this build linked SQLCipher and can open encrypted workspace DBs. */
  storageReady: boolean
  /** Configured embedding dims (BGE-small = 512). */
  dims: number
}

/** Citation-aware hierarchical chunker for the host ingest path. */
export declare function chunkDocument(input: ChunkDocumentNapiInput): Array<ChunkDocumentNapiOutput>

/** Input for `chunkDocument` (hierarchical citation-aware chunker). */
export interface ChunkDocumentNapiInput {
  docId: string
  text: string
  sourceUri: string
  page?: number
}

/** One chunk from `chunkDocument`. */
export interface ChunkDocumentNapiOutput {
  chunkId: string
  docId: string
  text: string
  chunkIndex: number
  tokenCount: number
  parentChunkId?: string
  chunkType: string
  sectionId?: string
  sectionNumber?: string
  sectionTitle?: string
  breadcrumbPath?: string
  sourceUri: string
  page?: number
  heading?: string
  charStart?: number
  charEnd?: number
}

/** Close the open workspace, persist `vectors.usearch`, drop key material. */
export declare function closeWorkspace(): OpResult

/** Embed a batch of texts (BGE-small when loaded; fail-soft if model missing). */
export declare function embedBatch(texts: Array<string>): EmbedBatchResult

/** Result of `embedBatch`. */
export interface EmbedBatchResult {
  ok: boolean
  error?: string
  embeddings?: Array<Array<number>>
  dims: number
}

/** Chunk row for `indexChunks`. */
export interface IndexChunkInput {
  chunkId: string
  text: string
  chunkIndex: number
  tokenCount?: number
  parentChunkId?: string
  chunkType?: string
  sectionId?: string
  sectionNumber?: string
  sectionTitle?: string
  breadcrumbPath?: string
  metadataJson?: string
  sourceUri?: string
  page?: number
  heading?: string
  charStart?: number
  charEnd?: number
}

/** Index document chunks into SQLCipher + usearch. */
export declare function indexChunks(doc: IndexDocumentInput, chunks: Array<IndexChunkInput>): OpResult

/** Document metadata for `indexChunks`. */
export interface IndexDocumentInput {
  id: string
  path: string
  filename: string
  filetype: string
  filesize: number
  checksum: string
  scope: string
  isCoreReference: boolean
  metadataJson?: string
  createdAt: string
  lastIndexedAt: string
}

/** Open encrypted chunk DB + usearch index under `root_dir`. */
export declare function openWorkspace(rootDir: string, dekBytes: Buffer): OpResult

/** Status object for mutating N-API calls (avoids `napi::Error` so `cargo test` can link). */
export interface OpResult {
  ok: boolean
  error?: string
  /** Optional count (chunks indexed / removed). */
  count?: number
}

/** Health check for the native addon. */
export declare function ping(): string

/** Index statistics. */
export interface RagStats {
  documents: number
  chunks: number
  /** usearch vector count when a workspace is open. */
  vectors: number
  /** tantivy live document count when a workspace is open. */
  textDocs: number
}

/** Remove a document and its vectors from the open workspace. */
export declare function removeDoc(docId: string): OpResult

/**
 * Hybrid BM25 + vector search with RRF fusion (k=20) and optional CE rerank.
 *
 * Fail-closed when the embed model is missing (same as `indexChunks`).
 * Degrades to hybrid+QP top-`finalK` when the cross-encoder is missing.
 */
export declare function search(query: string, opts: SearchOptions): SearchResult

/** Options for hybrid `search`. */
export interface SearchOptions {
  /**
   * Final result count after CE (or hybrid degrade).
   * Hybrid/RRF candidate pool = finalK × 4; CE trims to finalK when loaded.
   */
  finalK: number
  /**
   * `core_reference` | `case_index` | `all` (default `all`).
   * Explicit `core_reference` / `case_index` wins over QP routing for every sub-search.
   */
  scope?: string
}

/** Result of `search`. */
export interface SearchResult {
  ok: boolean
  error?: string
  results: Array<SearchResultItem>
}

/** One hybrid search hit (hydrated citation fields). */
export interface SearchResultItem {
  chunkId: string
  docId: string
  text: string
  fusedScore: number
  bm25Rank?: number
  vectorRank?: number
  sourceUri?: string
  page?: number
  heading?: string
  charStart?: number
  charEnd?: number
  sectionTitle?: string
  breadcrumbPath?: string
  chunkType?: string
  scope: string
}

/** Workspace index stats. */
export declare function stats(): RagStats

/** Package / crate version. */
export declare function version(): string
